name: vision1
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'



dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  dartz: ^0.10.1
  shared_preferences: ^2.2.3
  flutter_otp_text_field: ^1.1.3+2
  http: ^1.2.0
  lottie: ^3.1.0
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  colorful_safe_area: ^1.0.0
#  google_fonts: ^6.2.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/images/app_logo.png"
    min_sdk_android: 21
    flutter_test:
    sdk: flutter clean
    flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/lottie/
  # example:
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
          weight: 700

    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Bold.ttf
          weight: 700
